project:
  type: website
  output-dir: docs

website:
  title: "javirudolph"
  # reader-mode: true
  # repo-url: https://github.com/samanthacsik/samanthacsik.github.io
  # repo-actions: [edit, issue]
  site-url: https://javirudolph.github.io/
  # favicon: images/mywebsiteicon.png
  navbar:
    title: false
    # logo: images/mylogo.png
    # logo-alt: "alt-text for logo"
    right:
      - href: index.qmd
        text: home
      - about.qmd
      - posts.qmd # add your listing page file to your navbar, just like you would any other new web page
      # - href: talks_workshops.qmd
      #   text: talks & workshops
      # - href: courses.qmd
      #   text: courses
      # - href: projects.qmd
      #   text: projects
      - text: get in touch!
        menu:
          - icon: linkedin
            text: LinkedIn
            href: https://www.linkedin.com/in/javirudolph/
            target: _blank
          - icon: envelope
            text: email
            href: mailto:f.javierarudolph@gmail.com
      - icon: github
        href: https://github.com/javirudolph/
        target: _blank
  page-footer: 
    background: light
    left: © 2024 Francisca Javiera Rudolph Ph.D.
    right: This website was built with [Quarto](https://quarto.org/){target=_blank}

format:
  html:
    page-layout: full
    sidebar: false
    theme: cosmo
    css: styles.css
    toc: true
    